/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2235;

import edu.isu.cs2235.structures.Trie;
import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

public class TrieTest {

    private Trie fixture;

    @Before
    public void setUp() {
        fixture = new Trie();
    }

    @Test
    public void testAddWord() {
        fixture.addWord("testword");

        assertTrue("Trie does not contain word previously added.", fixture.contains("testword"));
    }

    @Test
    public void testOverwritingSmallerWords() {
        fixture.addWord("abra");
        fixture.addWord("abracadabra");

        assertTrue("When adding a word, subsets of the word appear to be overwritten.", fixture.contains("abra"));
    }

    @Test
    public void testCaseInsensitive() {
        fixture.addWord("WoRd");

        assertTrue("Trie should not be case-sensitive.", fixture.contains("wOrD"));
    }

    @Test
    public void testContains() {
        assertFalse("Trie contains word that was never added.", fixture.contains("loveyoukyla"));
    }
}
